import type { Metadata } from 'next';
import './globals.css';
import Navbar from '@/components/Navbar';
import { Inter } from 'next/font/google';
import { ThemeProvider } from '@/components/theme-provider';
import Footer from '@/components/Footer';
import { ClerkProvider } from '@clerk/nextjs';

const inter = Inter({
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: 'Next js Blog App',
	description: 'Generated by create next app',
};

export default function RootLayout({children,}: Readonly<{ children: React.ReactNode;}>) {
	return (
		<ClerkProvider>
			<html
				lang='en'
				suppressHydrationWarning>
				<body className={`${inter.className}`}>
					<ThemeProvider
						attribute='class'
						defaultTheme='system'
						enableSystem
						disableTransitionOnChange>
						<main className='mx-auto md:max-w-[80%] px-4 w-full'>
							<Navbar />
							{children}
							<Footer />
						</main>
					</ThemeProvider>
				</body>
			</html>
		</ClerkProvider>
	);
}
